2024-10-27 00:07:55,086 INFO     >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2024-10-27 00:07:55,088 INFO     Starting up
2024-10-27 00:07:55,088 INFO     Time delay default is: 300 seconds
2024-10-27 00:07:55,088 INFO     Create Gracekiller class
2024-10-27 00:07:55,088 INFO     End Start up. Starting while loop
2024-10-27 00:07:55,088 INFO     >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2024-10-27 00:07:55,088 INFO     --------------------------------------------------------------
2024-10-27 00:07:55,389 ERROR    Traceback (most recent call last):
2024-10-27 00:07:55,389 ERROR      File "/var/www/feeder/feeder/feederTimeService.py", line 179, in <module>
2024-10-27 00:07:55,390 ERROR    output = commonTasks.update_spreadsheet()
2024-10-27 00:07:55,390 ERROR    ^
2024-10-27 00:07:55,390 ERROR    ^
2024-10-27 00:07:55,390 ERROR    ^
2024-10-27 00:07:55,390 ERROR    ^
2024-10-27 00:07:55,390 ERROR    ^
2024-10-27 00:07:55,390 ERROR    ^
2024-10-27 00:07:55,390 ERROR    ^
2024-10-27 00:07:55,390 ERROR    ^
2024-10-27 00:07:55,390 ERROR    ^
2024-10-27 00:07:55,390 ERROR    ^
2024-10-27 00:07:55,390 ERROR    ^
2024-10-27 00:07:55,390 ERROR    ^
2024-10-27 00:07:55,390 ERROR    ^
2024-10-27 00:07:55,390 ERROR    ^
2024-10-27 00:07:55,390 ERROR    ^
2024-10-27 00:07:55,390 ERROR    ^
2024-10-27 00:07:55,390 ERROR    ^
2024-10-27 00:07:55,390 ERROR    ^
2024-10-27 00:07:55,390 ERROR    ^
2024-10-27 00:07:55,390 ERROR    ^
2024-10-27 00:07:55,390 ERROR    ^
2024-10-27 00:07:55,390 ERROR    ^
2024-10-27 00:07:55,390 ERROR    ^
2024-10-27 00:07:55,390 ERROR    ^
2024-10-27 00:07:55,390 ERROR    ^
2024-10-27 00:07:55,390 ERROR    ^
2024-10-27 00:07:55,390 ERROR    ^
2024-10-27 00:07:55,390 ERROR    ^
2024-10-27 00:07:55,390 ERROR    ^
2024-10-27 00:07:55,390 ERROR    ^
2024-10-27 00:07:55,390 ERROR    ^
2024-10-27 00:07:55,390 ERROR    ^
2024-10-27 00:07:55,390 ERROR      File "/var/www/feeder/feeder/commonTasks.py", line 189, in update_spreadsheet
2024-10-27 00:07:55,393 ERROR    sheet = client.open(spreadsheetFileName).sheet1
2024-10-27 00:07:55,393 ERROR    ^
2024-10-27 00:07:55,393 ERROR    ^
2024-10-27 00:07:55,393 ERROR    ^
2024-10-27 00:07:55,393 ERROR    ^
2024-10-27 00:07:55,393 ERROR    ^
2024-10-27 00:07:55,393 ERROR    ^
2024-10-27 00:07:55,393 ERROR    ^
2024-10-27 00:07:55,393 ERROR    ^
2024-10-27 00:07:55,393 ERROR    ^
2024-10-27 00:07:55,393 ERROR    ^
2024-10-27 00:07:55,393 ERROR    ^
2024-10-27 00:07:55,394 ERROR    ^
2024-10-27 00:07:55,394 ERROR    ^
2024-10-27 00:07:55,394 ERROR    ^
2024-10-27 00:07:55,394 ERROR    ^
2024-10-27 00:07:55,394 ERROR    ^
2024-10-27 00:07:55,394 ERROR    ^
2024-10-27 00:07:55,394 ERROR    ^
2024-10-27 00:07:55,394 ERROR    ^
2024-10-27 00:07:55,394 ERROR    ^
2024-10-27 00:07:55,394 ERROR    ^
2024-10-27 00:07:55,394 ERROR    ^
2024-10-27 00:07:55,394 ERROR    ^
2024-10-27 00:07:55,394 ERROR    ^
2024-10-27 00:07:55,394 ERROR    ^
2024-10-27 00:07:55,394 ERROR    ^
2024-10-27 00:07:55,394 ERROR    ^
2024-10-27 00:07:55,394 ERROR    ^
2024-10-27 00:07:55,394 ERROR    ^
2024-10-27 00:07:55,394 ERROR    ^
2024-10-27 00:07:55,394 ERROR    ^
2024-10-27 00:07:55,394 ERROR    ^
2024-10-27 00:07:55,394 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/gspread/client.py", line 132, in open
2024-10-27 00:07:55,395 ERROR    spreadsheet_files, response = self._list_spreadsheet_files(title, folder_id)
2024-10-27 00:07:55,395 ERROR    ^
2024-10-27 00:07:55,395 ERROR    ^
2024-10-27 00:07:55,395 ERROR    ^
2024-10-27 00:07:55,395 ERROR    ^
2024-10-27 00:07:55,395 ERROR    ^
2024-10-27 00:07:55,395 ERROR    ^
2024-10-27 00:07:55,395 ERROR    ^
2024-10-27 00:07:55,395 ERROR    ^
2024-10-27 00:07:55,395 ERROR    ^
2024-10-27 00:07:55,395 ERROR    ^
2024-10-27 00:07:55,395 ERROR    ^
2024-10-27 00:07:55,395 ERROR    ^
2024-10-27 00:07:55,395 ERROR    ^
2024-10-27 00:07:55,395 ERROR    ^
2024-10-27 00:07:55,395 ERROR    ^
2024-10-27 00:07:55,395 ERROR    ^
2024-10-27 00:07:55,395 ERROR    ^
2024-10-27 00:07:55,395 ERROR    ^
2024-10-27 00:07:55,395 ERROR    ^
2024-10-27 00:07:55,395 ERROR    ^
2024-10-27 00:07:55,395 ERROR    ^
2024-10-27 00:07:55,395 ERROR    ^
2024-10-27 00:07:55,395 ERROR    ^
2024-10-27 00:07:55,395 ERROR    ^
2024-10-27 00:07:55,395 ERROR    ^
2024-10-27 00:07:55,395 ERROR    ^
2024-10-27 00:07:55,395 ERROR    ^
2024-10-27 00:07:55,395 ERROR    ^
2024-10-27 00:07:55,395 ERROR    ^
2024-10-27 00:07:55,395 ERROR    ^
2024-10-27 00:07:55,395 ERROR    ^
2024-10-27 00:07:55,395 ERROR    ^
2024-10-27 00:07:55,396 ERROR    ^
2024-10-27 00:07:55,396 ERROR    ^
2024-10-27 00:07:55,396 ERROR    ^
2024-10-27 00:07:55,396 ERROR    ^
2024-10-27 00:07:55,396 ERROR    ^
2024-10-27 00:07:55,396 ERROR    ^
2024-10-27 00:07:55,396 ERROR    ^
2024-10-27 00:07:55,396 ERROR    ^
2024-10-27 00:07:55,396 ERROR    ^
2024-10-27 00:07:55,396 ERROR    ^
2024-10-27 00:07:55,396 ERROR    ^
2024-10-27 00:07:55,396 ERROR    ^
2024-10-27 00:07:55,396 ERROR    ^
2024-10-27 00:07:55,396 ERROR    ^
2024-10-27 00:07:55,396 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/gspread/client.py", line 105, in _list_spreadsheet_files
2024-10-27 00:07:55,396 ERROR    response = self.http_client.request("get", url, params=params)
2024-10-27 00:07:55,396 ERROR    ^
2024-10-27 00:07:55,396 ERROR    ^
2024-10-27 00:07:55,396 ERROR    ^
2024-10-27 00:07:55,396 ERROR    ^
2024-10-27 00:07:55,396 ERROR    ^
2024-10-27 00:07:55,396 ERROR    ^
2024-10-27 00:07:55,396 ERROR    ^
2024-10-27 00:07:55,396 ERROR    ^
2024-10-27 00:07:55,396 ERROR    ^
2024-10-27 00:07:55,396 ERROR    ^
2024-10-27 00:07:55,396 ERROR    ^
2024-10-27 00:07:55,396 ERROR    ^
2024-10-27 00:07:55,396 ERROR    ^
2024-10-27 00:07:55,396 ERROR    ^
2024-10-27 00:07:55,396 ERROR    ^
2024-10-27 00:07:55,396 ERROR    ^
2024-10-27 00:07:55,396 ERROR    ^
2024-10-27 00:07:55,396 ERROR    ^
2024-10-27 00:07:55,396 ERROR    ^
2024-10-27 00:07:55,396 ERROR    ^
2024-10-27 00:07:55,396 ERROR    ^
2024-10-27 00:07:55,396 ERROR    ^
2024-10-27 00:07:55,397 ERROR    ^
2024-10-27 00:07:55,397 ERROR    ^
2024-10-27 00:07:55,397 ERROR    ^
2024-10-27 00:07:55,397 ERROR    ^
2024-10-27 00:07:55,397 ERROR    ^
2024-10-27 00:07:55,397 ERROR    ^
2024-10-27 00:07:55,397 ERROR    ^
2024-10-27 00:07:55,397 ERROR    ^
2024-10-27 00:07:55,397 ERROR    ^
2024-10-27 00:07:55,397 ERROR    ^
2024-10-27 00:07:55,397 ERROR    ^
2024-10-27 00:07:55,397 ERROR    ^
2024-10-27 00:07:55,397 ERROR    ^
2024-10-27 00:07:55,397 ERROR    ^
2024-10-27 00:07:55,397 ERROR    ^
2024-10-27 00:07:55,397 ERROR    ^
2024-10-27 00:07:55,397 ERROR    ^
2024-10-27 00:07:55,397 ERROR    ^
2024-10-27 00:07:55,397 ERROR    ^
2024-10-27 00:07:55,397 ERROR    ^
2024-10-27 00:07:55,397 ERROR    ^
2024-10-27 00:07:55,397 ERROR    ^
2024-10-27 00:07:55,397 ERROR    ^
2024-10-27 00:07:55,397 ERROR    ^
2024-10-27 00:07:55,397 ERROR    ^
2024-10-27 00:07:55,397 ERROR    ^
2024-10-27 00:07:55,397 ERROR    ^
2024-10-27 00:07:55,397 ERROR    ^
2024-10-27 00:07:55,397 ERROR    ^
2024-10-27 00:07:55,397 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/gspread/http_client.py", line 114, in request
2024-10-27 00:07:55,398 ERROR    response = self.session.request(
2024-10-27 00:07:55,398 ERROR    ^
2024-10-27 00:07:55,398 ERROR    ^
2024-10-27 00:07:55,398 ERROR    ^
2024-10-27 00:07:55,398 ERROR    ^
2024-10-27 00:07:55,398 ERROR    ^
2024-10-27 00:07:55,398 ERROR    ^
2024-10-27 00:07:55,398 ERROR    ^
2024-10-27 00:07:55,398 ERROR    ^
2024-10-27 00:07:55,398 ERROR    ^
2024-10-27 00:07:55,398 ERROR    ^
2024-10-27 00:07:55,398 ERROR    ^
2024-10-27 00:07:55,398 ERROR    ^
2024-10-27 00:07:55,398 ERROR    ^
2024-10-27 00:07:55,398 ERROR    ^
2024-10-27 00:07:55,398 ERROR    ^
2024-10-27 00:07:55,398 ERROR    ^
2024-10-27 00:07:55,398 ERROR    ^
2024-10-27 00:07:55,398 ERROR    ^
2024-10-27 00:07:55,398 ERROR    ^
2024-10-27 00:07:55,398 ERROR    ^
2024-10-27 00:07:55,398 ERROR    ^
2024-10-27 00:07:55,398 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/google/auth/transport/requests.py", line 534, in request
2024-10-27 00:07:55,399 ERROR    self.credentials.before_request(auth_request, method, url, request_headers)
2024-10-27 00:07:55,399 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/google/auth/credentials.py", line 228, in before_request
2024-10-27 00:07:55,400 ERROR    self._blocking_refresh(request)
2024-10-27 00:07:55,400 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/google/auth/credentials.py", line 191, in _blocking_refresh
2024-10-27 00:07:55,400 ERROR    self.refresh(request)
2024-10-27 00:07:55,400 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/google/oauth2/service_account.py", line 446, in refresh
2024-10-27 00:07:55,401 ERROR    access_token, expiry, _ = _client.jwt_grant(
2024-10-27 00:07:55,401 ERROR    ^
2024-10-27 00:07:55,401 ERROR    ^
2024-10-27 00:07:55,401 ERROR    ^
2024-10-27 00:07:55,401 ERROR    ^
2024-10-27 00:07:55,401 ERROR    ^
2024-10-27 00:07:55,401 ERROR    ^
2024-10-27 00:07:55,401 ERROR    ^
2024-10-27 00:07:55,401 ERROR    ^
2024-10-27 00:07:55,401 ERROR    ^
2024-10-27 00:07:55,401 ERROR    ^
2024-10-27 00:07:55,401 ERROR    ^
2024-10-27 00:07:55,401 ERROR    ^
2024-10-27 00:07:55,401 ERROR    ^
2024-10-27 00:07:55,401 ERROR    ^
2024-10-27 00:07:55,401 ERROR    ^
2024-10-27 00:07:55,401 ERROR    ^
2024-10-27 00:07:55,401 ERROR    ^
2024-10-27 00:07:55,401 ERROR    ^
2024-10-27 00:07:55,401 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/google/oauth2/_client.py", line 298, in jwt_grant
2024-10-27 00:07:55,402 ERROR    response_data = _token_endpoint_request(
2024-10-27 00:07:55,402 ERROR    ^
2024-10-27 00:07:55,402 ERROR    ^
2024-10-27 00:07:55,402 ERROR    ^
2024-10-27 00:07:55,402 ERROR    ^
2024-10-27 00:07:55,402 ERROR    ^
2024-10-27 00:07:55,402 ERROR    ^
2024-10-27 00:07:55,402 ERROR    ^
2024-10-27 00:07:55,402 ERROR    ^
2024-10-27 00:07:55,402 ERROR    ^
2024-10-27 00:07:55,402 ERROR    ^
2024-10-27 00:07:55,402 ERROR    ^
2024-10-27 00:07:55,402 ERROR    ^
2024-10-27 00:07:55,402 ERROR    ^
2024-10-27 00:07:55,402 ERROR    ^
2024-10-27 00:07:55,402 ERROR    ^
2024-10-27 00:07:55,402 ERROR    ^
2024-10-27 00:07:55,402 ERROR    ^
2024-10-27 00:07:55,402 ERROR    ^
2024-10-27 00:07:55,402 ERROR    ^
2024-10-27 00:07:55,402 ERROR    ^
2024-10-27 00:07:55,402 ERROR    ^
2024-10-27 00:07:55,402 ERROR    ^
2024-10-27 00:07:55,402 ERROR    ^
2024-10-27 00:07:55,402 ERROR    ^
2024-10-27 00:07:55,402 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/google/oauth2/_client.py", line 269, in _token_endpoint_request
2024-10-27 00:07:55,402 ERROR    _handle_error_response(response_data, retryable_error)
2024-10-27 00:07:55,402 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/google/oauth2/_client.py", line 68, in _handle_error_response
2024-10-27 00:07:55,403 ERROR    raise exceptions.RefreshError(
2024-10-27 00:07:55,403 ERROR    google.auth.exceptions
2024-10-27 00:07:55,403 ERROR    .
2024-10-27 00:07:55,403 ERROR    RefreshError
2024-10-27 00:07:55,403 ERROR    :
2024-10-27 00:07:55,403 ERROR    ('invalid_grant: Invalid JWT Signature.', {'error': 'invalid_grant', 'error_description': 'Invalid JWT Signature.'})
2024-10-27 00:07:55,403 ERROR    Exception ignored in:
2024-10-27 00:07:55,404 ERROR    <__main__.MyLogger object at 0xffff89490170>
2024-10-27 00:07:55,404 ERROR    AttributeError
2024-10-27 00:07:55,404 ERROR    :
2024-10-27 00:07:55,404 ERROR    'MyLogger' object has no attribute 'flush'
2024-10-27 00:07:55,404 ERROR    Exception ignored in sys.unraisablehook
2024-10-27 00:07:55,404 ERROR    :
2024-10-27 00:07:55,404 ERROR    <built-in function unraisablehook>
2024-10-27 00:07:55,404 ERROR    AttributeError
2024-10-27 00:07:55,404 ERROR    :
2024-10-27 00:07:55,404 ERROR    'MyLogger' object has no attribute 'flush'
2024-10-27 00:12:14,265 INFO     >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2024-10-27 00:12:14,266 INFO     Starting up
2024-10-27 00:12:14,266 INFO     Time delay default is: 300 seconds
2024-10-27 00:12:14,266 INFO     Create Gracekiller class
2024-10-27 00:12:14,266 INFO     End Start up. Starting while loop
2024-10-27 00:12:14,266 INFO     >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2024-10-27 00:12:14,266 INFO     --------------------------------------------------------------
2024-10-27 00:12:14,566 ERROR    Traceback (most recent call last):
2024-10-27 00:12:14,566 ERROR      File "/var/www/feeder/feeder/feederTimeService.py", line 179, in <module>
2024-10-27 00:12:14,566 ERROR    output = commonTasks.update_spreadsheet()
2024-10-27 00:12:14,566 ERROR    ^
2024-10-27 00:12:14,566 ERROR    ^
2024-10-27 00:12:14,566 ERROR    ^
2024-10-27 00:12:14,566 ERROR    ^
2024-10-27 00:12:14,566 ERROR    ^
2024-10-27 00:12:14,566 ERROR    ^
2024-10-27 00:12:14,566 ERROR    ^
2024-10-27 00:12:14,566 ERROR    ^
2024-10-27 00:12:14,566 ERROR    ^
2024-10-27 00:12:14,566 ERROR    ^
2024-10-27 00:12:14,566 ERROR    ^
2024-10-27 00:12:14,566 ERROR    ^
2024-10-27 00:12:14,566 ERROR    ^
2024-10-27 00:12:14,566 ERROR    ^
2024-10-27 00:12:14,566 ERROR    ^
2024-10-27 00:12:14,567 ERROR    ^
2024-10-27 00:12:14,567 ERROR    ^
2024-10-27 00:12:14,567 ERROR    ^
2024-10-27 00:12:14,567 ERROR    ^
2024-10-27 00:12:14,567 ERROR    ^
2024-10-27 00:12:14,567 ERROR    ^
2024-10-27 00:12:14,567 ERROR    ^
2024-10-27 00:12:14,567 ERROR    ^
2024-10-27 00:12:14,567 ERROR    ^
2024-10-27 00:12:14,567 ERROR    ^
2024-10-27 00:12:14,567 ERROR    ^
2024-10-27 00:12:14,567 ERROR    ^
2024-10-27 00:12:14,567 ERROR    ^
2024-10-27 00:12:14,567 ERROR    ^
2024-10-27 00:12:14,567 ERROR    ^
2024-10-27 00:12:14,567 ERROR    ^
2024-10-27 00:12:14,567 ERROR    ^
2024-10-27 00:12:14,567 ERROR      File "/var/www/feeder/feeder/commonTasks.py", line 189, in update_spreadsheet
2024-10-27 00:12:14,568 ERROR    sheet = client.open(spreadsheetFileName).sheet1
2024-10-27 00:12:14,568 ERROR    ^
2024-10-27 00:12:14,568 ERROR    ^
2024-10-27 00:12:14,568 ERROR    ^
2024-10-27 00:12:14,568 ERROR    ^
2024-10-27 00:12:14,568 ERROR    ^
2024-10-27 00:12:14,568 ERROR    ^
2024-10-27 00:12:14,568 ERROR    ^
2024-10-27 00:12:14,568 ERROR    ^
2024-10-27 00:12:14,568 ERROR    ^
2024-10-27 00:12:14,568 ERROR    ^
2024-10-27 00:12:14,568 ERROR    ^
2024-10-27 00:12:14,568 ERROR    ^
2024-10-27 00:12:14,568 ERROR    ^
2024-10-27 00:12:14,568 ERROR    ^
2024-10-27 00:12:14,568 ERROR    ^
2024-10-27 00:12:14,568 ERROR    ^
2024-10-27 00:12:14,568 ERROR    ^
2024-10-27 00:12:14,568 ERROR    ^
2024-10-27 00:12:14,568 ERROR    ^
2024-10-27 00:12:14,568 ERROR    ^
2024-10-27 00:12:14,568 ERROR    ^
2024-10-27 00:12:14,568 ERROR    ^
2024-10-27 00:12:14,568 ERROR    ^
2024-10-27 00:12:14,568 ERROR    ^
2024-10-27 00:12:14,568 ERROR    ^
2024-10-27 00:12:14,569 ERROR    ^
2024-10-27 00:12:14,569 ERROR    ^
2024-10-27 00:12:14,569 ERROR    ^
2024-10-27 00:12:14,569 ERROR    ^
2024-10-27 00:12:14,569 ERROR    ^
2024-10-27 00:12:14,569 ERROR    ^
2024-10-27 00:12:14,569 ERROR    ^
2024-10-27 00:12:14,569 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/gspread/client.py", line 132, in open
2024-10-27 00:12:14,569 ERROR    spreadsheet_files, response = self._list_spreadsheet_files(title, folder_id)
2024-10-27 00:12:14,570 ERROR    ^
2024-10-27 00:12:14,570 ERROR    ^
2024-10-27 00:12:14,570 ERROR    ^
2024-10-27 00:12:14,570 ERROR    ^
2024-10-27 00:12:14,570 ERROR    ^
2024-10-27 00:12:14,570 ERROR    ^
2024-10-27 00:12:14,570 ERROR    ^
2024-10-27 00:12:14,570 ERROR    ^
2024-10-27 00:12:14,570 ERROR    ^
2024-10-27 00:12:14,570 ERROR    ^
2024-10-27 00:12:14,570 ERROR    ^
2024-10-27 00:12:14,570 ERROR    ^
2024-10-27 00:12:14,570 ERROR    ^
2024-10-27 00:12:14,570 ERROR    ^
2024-10-27 00:12:14,570 ERROR    ^
2024-10-27 00:12:14,570 ERROR    ^
2024-10-27 00:12:14,570 ERROR    ^
2024-10-27 00:12:14,570 ERROR    ^
2024-10-27 00:12:14,570 ERROR    ^
2024-10-27 00:12:14,570 ERROR    ^
2024-10-27 00:12:14,570 ERROR    ^
2024-10-27 00:12:14,570 ERROR    ^
2024-10-27 00:12:14,570 ERROR    ^
2024-10-27 00:12:14,570 ERROR    ^
2024-10-27 00:12:14,570 ERROR    ^
2024-10-27 00:12:14,570 ERROR    ^
2024-10-27 00:12:14,570 ERROR    ^
2024-10-27 00:12:14,570 ERROR    ^
2024-10-27 00:12:14,570 ERROR    ^
2024-10-27 00:12:14,570 ERROR    ^
2024-10-27 00:12:14,570 ERROR    ^
2024-10-27 00:12:14,570 ERROR    ^
2024-10-27 00:12:14,570 ERROR    ^
2024-10-27 00:12:14,570 ERROR    ^
2024-10-27 00:12:14,570 ERROR    ^
2024-10-27 00:12:14,570 ERROR    ^
2024-10-27 00:12:14,570 ERROR    ^
2024-10-27 00:12:14,570 ERROR    ^
2024-10-27 00:12:14,571 ERROR    ^
2024-10-27 00:12:14,571 ERROR    ^
2024-10-27 00:12:14,571 ERROR    ^
2024-10-27 00:12:14,571 ERROR    ^
2024-10-27 00:12:14,571 ERROR    ^
2024-10-27 00:12:14,571 ERROR    ^
2024-10-27 00:12:14,571 ERROR    ^
2024-10-27 00:12:14,571 ERROR    ^
2024-10-27 00:12:14,571 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/gspread/client.py", line 105, in _list_spreadsheet_files
2024-10-27 00:12:14,571 ERROR    response = self.http_client.request("get", url, params=params)
2024-10-27 00:12:14,571 ERROR    ^
2024-10-27 00:12:14,571 ERROR    ^
2024-10-27 00:12:14,571 ERROR    ^
2024-10-27 00:12:14,571 ERROR    ^
2024-10-27 00:12:14,571 ERROR    ^
2024-10-27 00:12:14,571 ERROR    ^
2024-10-27 00:12:14,571 ERROR    ^
2024-10-27 00:12:14,571 ERROR    ^
2024-10-27 00:12:14,571 ERROR    ^
2024-10-27 00:12:14,571 ERROR    ^
2024-10-27 00:12:14,571 ERROR    ^
2024-10-27 00:12:14,571 ERROR    ^
2024-10-27 00:12:14,571 ERROR    ^
2024-10-27 00:12:14,571 ERROR    ^
2024-10-27 00:12:14,571 ERROR    ^
2024-10-27 00:12:14,571 ERROR    ^
2024-10-27 00:12:14,571 ERROR    ^
2024-10-27 00:12:14,571 ERROR    ^
2024-10-27 00:12:14,571 ERROR    ^
2024-10-27 00:12:14,571 ERROR    ^
2024-10-27 00:12:14,571 ERROR    ^
2024-10-27 00:12:14,571 ERROR    ^
2024-10-27 00:12:14,572 ERROR    ^
2024-10-27 00:12:14,572 ERROR    ^
2024-10-27 00:12:14,572 ERROR    ^
2024-10-27 00:12:14,572 ERROR    ^
2024-10-27 00:12:14,572 ERROR    ^
2024-10-27 00:12:14,572 ERROR    ^
2024-10-27 00:12:14,572 ERROR    ^
2024-10-27 00:12:14,572 ERROR    ^
2024-10-27 00:12:14,572 ERROR    ^
2024-10-27 00:12:14,572 ERROR    ^
2024-10-27 00:12:14,572 ERROR    ^
2024-10-27 00:12:14,572 ERROR    ^
2024-10-27 00:12:14,572 ERROR    ^
2024-10-27 00:12:14,572 ERROR    ^
2024-10-27 00:12:14,572 ERROR    ^
2024-10-27 00:12:14,572 ERROR    ^
2024-10-27 00:12:14,572 ERROR    ^
2024-10-27 00:12:14,572 ERROR    ^
2024-10-27 00:12:14,572 ERROR    ^
2024-10-27 00:12:14,572 ERROR    ^
2024-10-27 00:12:14,572 ERROR    ^
2024-10-27 00:12:14,572 ERROR    ^
2024-10-27 00:12:14,572 ERROR    ^
2024-10-27 00:12:14,572 ERROR    ^
2024-10-27 00:12:14,572 ERROR    ^
2024-10-27 00:12:14,572 ERROR    ^
2024-10-27 00:12:14,572 ERROR    ^
2024-10-27 00:12:14,572 ERROR    ^
2024-10-27 00:12:14,572 ERROR    ^
2024-10-27 00:12:14,572 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/gspread/http_client.py", line 114, in request
2024-10-27 00:12:14,573 ERROR    response = self.session.request(
2024-10-27 00:12:14,573 ERROR    ^
2024-10-27 00:12:14,573 ERROR    ^
2024-10-27 00:12:14,573 ERROR    ^
2024-10-27 00:12:14,573 ERROR    ^
2024-10-27 00:12:14,573 ERROR    ^
2024-10-27 00:12:14,573 ERROR    ^
2024-10-27 00:12:14,573 ERROR    ^
2024-10-27 00:12:14,573 ERROR    ^
2024-10-27 00:12:14,573 ERROR    ^
2024-10-27 00:12:14,573 ERROR    ^
2024-10-27 00:12:14,573 ERROR    ^
2024-10-27 00:12:14,573 ERROR    ^
2024-10-27 00:12:14,573 ERROR    ^
2024-10-27 00:12:14,573 ERROR    ^
2024-10-27 00:12:14,573 ERROR    ^
2024-10-27 00:12:14,573 ERROR    ^
2024-10-27 00:12:14,573 ERROR    ^
2024-10-27 00:12:14,573 ERROR    ^
2024-10-27 00:12:14,573 ERROR    ^
2024-10-27 00:12:14,573 ERROR    ^
2024-10-27 00:12:14,573 ERROR    ^
2024-10-27 00:12:14,573 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/google/auth/transport/requests.py", line 534, in request
2024-10-27 00:12:14,574 ERROR    self.credentials.before_request(auth_request, method, url, request_headers)
2024-10-27 00:12:14,574 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/google/auth/credentials.py", line 228, in before_request
2024-10-27 00:12:14,575 ERROR    self._blocking_refresh(request)
2024-10-27 00:12:14,575 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/google/auth/credentials.py", line 191, in _blocking_refresh
2024-10-27 00:12:14,575 ERROR    self.refresh(request)
2024-10-27 00:12:14,575 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/google/oauth2/service_account.py", line 446, in refresh
2024-10-27 00:12:14,576 ERROR    access_token, expiry, _ = _client.jwt_grant(
2024-10-27 00:12:14,576 ERROR    ^
2024-10-27 00:12:14,576 ERROR    ^
2024-10-27 00:12:14,576 ERROR    ^
2024-10-27 00:12:14,576 ERROR    ^
2024-10-27 00:12:14,576 ERROR    ^
2024-10-27 00:12:14,576 ERROR    ^
2024-10-27 00:12:14,576 ERROR    ^
2024-10-27 00:12:14,576 ERROR    ^
2024-10-27 00:12:14,576 ERROR    ^
2024-10-27 00:12:14,576 ERROR    ^
2024-10-27 00:12:14,576 ERROR    ^
2024-10-27 00:12:14,576 ERROR    ^
2024-10-27 00:12:14,576 ERROR    ^
2024-10-27 00:12:14,576 ERROR    ^
2024-10-27 00:12:14,576 ERROR    ^
2024-10-27 00:12:14,576 ERROR    ^
2024-10-27 00:12:14,576 ERROR    ^
2024-10-27 00:12:14,576 ERROR    ^
2024-10-27 00:12:14,576 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/google/oauth2/_client.py", line 298, in jwt_grant
2024-10-27 00:12:14,577 ERROR    response_data = _token_endpoint_request(
2024-10-27 00:12:14,577 ERROR    ^
2024-10-27 00:12:14,577 ERROR    ^
2024-10-27 00:12:14,577 ERROR    ^
2024-10-27 00:12:14,577 ERROR    ^
2024-10-27 00:12:14,577 ERROR    ^
2024-10-27 00:12:14,577 ERROR    ^
2024-10-27 00:12:14,577 ERROR    ^
2024-10-27 00:12:14,577 ERROR    ^
2024-10-27 00:12:14,577 ERROR    ^
2024-10-27 00:12:14,577 ERROR    ^
2024-10-27 00:12:14,577 ERROR    ^
2024-10-27 00:12:14,577 ERROR    ^
2024-10-27 00:12:14,577 ERROR    ^
2024-10-27 00:12:14,577 ERROR    ^
2024-10-27 00:12:14,577 ERROR    ^
2024-10-27 00:12:14,577 ERROR    ^
2024-10-27 00:12:14,577 ERROR    ^
2024-10-27 00:12:14,577 ERROR    ^
2024-10-27 00:12:14,577 ERROR    ^
2024-10-27 00:12:14,577 ERROR    ^
2024-10-27 00:12:14,577 ERROR    ^
2024-10-27 00:12:14,577 ERROR    ^
2024-10-27 00:12:14,577 ERROR    ^
2024-10-27 00:12:14,577 ERROR    ^
2024-10-27 00:12:14,577 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/google/oauth2/_client.py", line 269, in _token_endpoint_request
2024-10-27 00:12:14,577 ERROR    _handle_error_response(response_data, retryable_error)
2024-10-27 00:12:14,577 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/google/oauth2/_client.py", line 68, in _handle_error_response
2024-10-27 00:12:14,578 ERROR    raise exceptions.RefreshError(
2024-10-27 00:12:14,578 ERROR    google.auth.exceptions
2024-10-27 00:12:14,578 ERROR    .
2024-10-27 00:12:14,578 ERROR    RefreshError
2024-10-27 00:12:14,578 ERROR    :
2024-10-27 00:12:14,578 ERROR    ('invalid_grant: Invalid JWT Signature.', {'error': 'invalid_grant', 'error_description': 'Invalid JWT Signature.'})
2024-10-27 00:12:14,578 ERROR    Exception ignored in:
2024-10-27 00:12:14,578 ERROR    <__main__.MyLogger object at 0xffff9911c350>
2024-10-27 00:12:14,578 ERROR    AttributeError
2024-10-27 00:12:14,578 ERROR    :
2024-10-27 00:12:14,578 ERROR    'MyLogger' object has no attribute 'flush'
2024-10-27 00:12:14,578 ERROR    Exception ignored in sys.unraisablehook
2024-10-27 00:12:14,578 ERROR    :
2024-10-27 00:12:14,579 ERROR    <built-in function unraisablehook>
2024-10-27 00:12:14,579 ERROR    AttributeError
2024-10-27 00:12:14,579 ERROR    :
2024-10-27 00:12:14,579 ERROR    'MyLogger' object has no attribute 'flush'
2024-10-27 00:21:10,432 INFO     >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2024-10-27 00:21:10,432 INFO     Starting up
2024-10-27 00:21:10,432 INFO     Time delay default is: 300 seconds
2024-10-27 00:21:10,432 INFO     Create Gracekiller class
2024-10-27 00:21:10,432 INFO     End Start up. Starting while loop
2024-10-27 00:21:10,432 INFO     >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2024-10-27 00:21:10,433 INFO     --------------------------------------------------------------
2024-10-27 00:21:10,743 ERROR    Traceback (most recent call last):
2024-10-27 00:21:10,743 ERROR      File "/var/www/feeder/feeder/feederTimeService.py", line 179, in <module>
2024-10-27 00:21:10,743 ERROR    output = commonTasks.update_spreadsheet()
2024-10-27 00:21:10,743 ERROR    ^
2024-10-27 00:21:10,743 ERROR    ^
2024-10-27 00:21:10,743 ERROR    ^
2024-10-27 00:21:10,743 ERROR    ^
2024-10-27 00:21:10,743 ERROR    ^
2024-10-27 00:21:10,743 ERROR    ^
2024-10-27 00:21:10,743 ERROR    ^
2024-10-27 00:21:10,743 ERROR    ^
2024-10-27 00:21:10,743 ERROR    ^
2024-10-27 00:21:10,743 ERROR    ^
2024-10-27 00:21:10,743 ERROR    ^
2024-10-27 00:21:10,743 ERROR    ^
2024-10-27 00:21:10,743 ERROR    ^
2024-10-27 00:21:10,743 ERROR    ^
2024-10-27 00:21:10,743 ERROR    ^
2024-10-27 00:21:10,743 ERROR    ^
2024-10-27 00:21:10,743 ERROR    ^
2024-10-27 00:21:10,743 ERROR    ^
2024-10-27 00:21:10,743 ERROR    ^
2024-10-27 00:21:10,743 ERROR    ^
2024-10-27 00:21:10,743 ERROR    ^
2024-10-27 00:21:10,743 ERROR    ^
2024-10-27 00:21:10,743 ERROR    ^
2024-10-27 00:21:10,743 ERROR    ^
2024-10-27 00:21:10,744 ERROR    ^
2024-10-27 00:21:10,744 ERROR    ^
2024-10-27 00:21:10,744 ERROR    ^
2024-10-27 00:21:10,744 ERROR    ^
2024-10-27 00:21:10,744 ERROR    ^
2024-10-27 00:21:10,744 ERROR    ^
2024-10-27 00:21:10,744 ERROR    ^
2024-10-27 00:21:10,744 ERROR    ^
2024-10-27 00:21:10,744 ERROR      File "/var/www/feeder/feeder/commonTasks.py", line 189, in update_spreadsheet
2024-10-27 00:21:10,745 ERROR    sheet = client.open(spreadsheetFileName).sheet1
2024-10-27 00:21:10,745 ERROR    ^
2024-10-27 00:21:10,745 ERROR    ^
2024-10-27 00:21:10,745 ERROR    ^
2024-10-27 00:21:10,745 ERROR    ^
2024-10-27 00:21:10,745 ERROR    ^
2024-10-27 00:21:10,745 ERROR    ^
2024-10-27 00:21:10,745 ERROR    ^
2024-10-27 00:21:10,745 ERROR    ^
2024-10-27 00:21:10,745 ERROR    ^
2024-10-27 00:21:10,745 ERROR    ^
2024-10-27 00:21:10,745 ERROR    ^
2024-10-27 00:21:10,745 ERROR    ^
2024-10-27 00:21:10,745 ERROR    ^
2024-10-27 00:21:10,745 ERROR    ^
2024-10-27 00:21:10,745 ERROR    ^
2024-10-27 00:21:10,745 ERROR    ^
2024-10-27 00:21:10,745 ERROR    ^
2024-10-27 00:21:10,745 ERROR    ^
2024-10-27 00:21:10,745 ERROR    ^
2024-10-27 00:21:10,745 ERROR    ^
2024-10-27 00:21:10,745 ERROR    ^
2024-10-27 00:21:10,745 ERROR    ^
2024-10-27 00:21:10,745 ERROR    ^
2024-10-27 00:21:10,745 ERROR    ^
2024-10-27 00:21:10,745 ERROR    ^
2024-10-27 00:21:10,745 ERROR    ^
2024-10-27 00:21:10,745 ERROR    ^
2024-10-27 00:21:10,745 ERROR    ^
2024-10-27 00:21:10,745 ERROR    ^
2024-10-27 00:21:10,745 ERROR    ^
2024-10-27 00:21:10,745 ERROR    ^
2024-10-27 00:21:10,745 ERROR    ^
2024-10-27 00:21:10,745 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/gspread/client.py", line 132, in open
2024-10-27 00:21:10,747 ERROR    spreadsheet_files, response = self._list_spreadsheet_files(title, folder_id)
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR    ^
2024-10-27 00:21:10,748 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/gspread/client.py", line 105, in _list_spreadsheet_files
2024-10-27 00:21:10,749 ERROR    response = self.http_client.request("get", url, params=params)
2024-10-27 00:21:10,749 ERROR    ^
2024-10-27 00:21:10,749 ERROR    ^
2024-10-27 00:21:10,749 ERROR    ^
2024-10-27 00:21:10,749 ERROR    ^
2024-10-27 00:21:10,749 ERROR    ^
2024-10-27 00:21:10,749 ERROR    ^
2024-10-27 00:21:10,749 ERROR    ^
2024-10-27 00:21:10,749 ERROR    ^
2024-10-27 00:21:10,749 ERROR    ^
2024-10-27 00:21:10,749 ERROR    ^
2024-10-27 00:21:10,749 ERROR    ^
2024-10-27 00:21:10,749 ERROR    ^
2024-10-27 00:21:10,749 ERROR    ^
2024-10-27 00:21:10,749 ERROR    ^
2024-10-27 00:21:10,749 ERROR    ^
2024-10-27 00:21:10,749 ERROR    ^
2024-10-27 00:21:10,749 ERROR    ^
2024-10-27 00:21:10,749 ERROR    ^
2024-10-27 00:21:10,749 ERROR    ^
2024-10-27 00:21:10,749 ERROR    ^
2024-10-27 00:21:10,749 ERROR    ^
2024-10-27 00:21:10,749 ERROR    ^
2024-10-27 00:21:10,749 ERROR    ^
2024-10-27 00:21:10,749 ERROR    ^
2024-10-27 00:21:10,749 ERROR    ^
2024-10-27 00:21:10,749 ERROR    ^
2024-10-27 00:21:10,749 ERROR    ^
2024-10-27 00:21:10,749 ERROR    ^
2024-10-27 00:21:10,749 ERROR    ^
2024-10-27 00:21:10,749 ERROR    ^
2024-10-27 00:21:10,749 ERROR    ^
2024-10-27 00:21:10,749 ERROR    ^
2024-10-27 00:21:10,749 ERROR    ^
2024-10-27 00:21:10,749 ERROR    ^
2024-10-27 00:21:10,749 ERROR    ^
2024-10-27 00:21:10,749 ERROR    ^
2024-10-27 00:21:10,749 ERROR    ^
2024-10-27 00:21:10,749 ERROR    ^
2024-10-27 00:21:10,749 ERROR    ^
2024-10-27 00:21:10,750 ERROR    ^
2024-10-27 00:21:10,750 ERROR    ^
2024-10-27 00:21:10,750 ERROR    ^
2024-10-27 00:21:10,750 ERROR    ^
2024-10-27 00:21:10,750 ERROR    ^
2024-10-27 00:21:10,750 ERROR    ^
2024-10-27 00:21:10,750 ERROR    ^
2024-10-27 00:21:10,750 ERROR    ^
2024-10-27 00:21:10,750 ERROR    ^
2024-10-27 00:21:10,750 ERROR    ^
2024-10-27 00:21:10,750 ERROR    ^
2024-10-27 00:21:10,750 ERROR    ^
2024-10-27 00:21:10,750 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/gspread/http_client.py", line 114, in request
2024-10-27 00:21:10,752 ERROR    response = self.session.request(
2024-10-27 00:21:10,752 ERROR    ^
2024-10-27 00:21:10,752 ERROR    ^
2024-10-27 00:21:10,752 ERROR    ^
2024-10-27 00:21:10,752 ERROR    ^
2024-10-27 00:21:10,752 ERROR    ^
2024-10-27 00:21:10,752 ERROR    ^
2024-10-27 00:21:10,752 ERROR    ^
2024-10-27 00:21:10,752 ERROR    ^
2024-10-27 00:21:10,752 ERROR    ^
2024-10-27 00:21:10,752 ERROR    ^
2024-10-27 00:21:10,752 ERROR    ^
2024-10-27 00:21:10,752 ERROR    ^
2024-10-27 00:21:10,752 ERROR    ^
2024-10-27 00:21:10,752 ERROR    ^
2024-10-27 00:21:10,752 ERROR    ^
2024-10-27 00:21:10,752 ERROR    ^
2024-10-27 00:21:10,752 ERROR    ^
2024-10-27 00:21:10,752 ERROR    ^
2024-10-27 00:21:10,752 ERROR    ^
2024-10-27 00:21:10,752 ERROR    ^
2024-10-27 00:21:10,752 ERROR    ^
2024-10-27 00:21:10,752 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/google/auth/transport/requests.py", line 534, in request
2024-10-27 00:21:10,755 ERROR    self.credentials.before_request(auth_request, method, url, request_headers)
2024-10-27 00:21:10,755 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/google/auth/credentials.py", line 228, in before_request
2024-10-27 00:21:10,757 ERROR    self._blocking_refresh(request)
2024-10-27 00:21:10,757 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/google/auth/credentials.py", line 191, in _blocking_refresh
2024-10-27 00:21:10,757 ERROR    self.refresh(request)
2024-10-27 00:21:10,757 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/google/oauth2/service_account.py", line 446, in refresh
2024-10-27 00:21:10,760 ERROR    access_token, expiry, _ = _client.jwt_grant(
2024-10-27 00:21:10,760 ERROR    ^
2024-10-27 00:21:10,760 ERROR    ^
2024-10-27 00:21:10,760 ERROR    ^
2024-10-27 00:21:10,761 ERROR    ^
2024-10-27 00:21:10,761 ERROR    ^
2024-10-27 00:21:10,761 ERROR    ^
2024-10-27 00:21:10,761 ERROR    ^
2024-10-27 00:21:10,761 ERROR    ^
2024-10-27 00:21:10,761 ERROR    ^
2024-10-27 00:21:10,761 ERROR    ^
2024-10-27 00:21:10,761 ERROR    ^
2024-10-27 00:21:10,761 ERROR    ^
2024-10-27 00:21:10,761 ERROR    ^
2024-10-27 00:21:10,761 ERROR    ^
2024-10-27 00:21:10,761 ERROR    ^
2024-10-27 00:21:10,761 ERROR    ^
2024-10-27 00:21:10,761 ERROR    ^
2024-10-27 00:21:10,761 ERROR    ^
2024-10-27 00:21:10,761 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/google/oauth2/_client.py", line 298, in jwt_grant
2024-10-27 00:21:10,762 ERROR    response_data = _token_endpoint_request(
2024-10-27 00:21:10,762 ERROR    ^
2024-10-27 00:21:10,762 ERROR    ^
2024-10-27 00:21:10,762 ERROR    ^
2024-10-27 00:21:10,763 ERROR    ^
2024-10-27 00:21:10,763 ERROR    ^
2024-10-27 00:21:10,763 ERROR    ^
2024-10-27 00:21:10,763 ERROR    ^
2024-10-27 00:21:10,763 ERROR    ^
2024-10-27 00:21:10,763 ERROR    ^
2024-10-27 00:21:10,763 ERROR    ^
2024-10-27 00:21:10,763 ERROR    ^
2024-10-27 00:21:10,763 ERROR    ^
2024-10-27 00:21:10,763 ERROR    ^
2024-10-27 00:21:10,763 ERROR    ^
2024-10-27 00:21:10,763 ERROR    ^
2024-10-27 00:21:10,763 ERROR    ^
2024-10-27 00:21:10,763 ERROR    ^
2024-10-27 00:21:10,763 ERROR    ^
2024-10-27 00:21:10,763 ERROR    ^
2024-10-27 00:21:10,763 ERROR    ^
2024-10-27 00:21:10,763 ERROR    ^
2024-10-27 00:21:10,763 ERROR    ^
2024-10-27 00:21:10,763 ERROR    ^
2024-10-27 00:21:10,763 ERROR    ^
2024-10-27 00:21:10,763 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/google/oauth2/_client.py", line 269, in _token_endpoint_request
2024-10-27 00:21:10,763 ERROR    _handle_error_response(response_data, retryable_error)
2024-10-27 00:21:10,763 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/google/oauth2/_client.py", line 68, in _handle_error_response
2024-10-27 00:21:10,764 ERROR    raise exceptions.RefreshError(
2024-10-27 00:21:10,764 ERROR    google.auth.exceptions
2024-10-27 00:21:10,764 ERROR    .
2024-10-27 00:21:10,764 ERROR    RefreshError
2024-10-27 00:21:10,764 ERROR    :
2024-10-27 00:21:10,764 ERROR    ('invalid_grant: Invalid JWT Signature.', {'error': 'invalid_grant', 'error_description': 'Invalid JWT Signature.'})
2024-10-27 00:21:10,764 ERROR    Exception ignored in:
2024-10-27 00:21:10,764 ERROR    <__main__.MyLogger object at 0xffffaa943890>
2024-10-27 00:21:10,764 ERROR    AttributeError
2024-10-27 00:21:10,765 ERROR    :
2024-10-27 00:21:10,765 ERROR    'MyLogger' object has no attribute 'flush'
2024-10-27 00:21:10,765 ERROR    Exception ignored in sys.unraisablehook
2024-10-27 00:21:10,765 ERROR    :
2024-10-27 00:21:10,765 ERROR    <built-in function unraisablehook>
2024-10-27 00:21:10,765 ERROR    AttributeError
2024-10-27 00:21:10,765 ERROR    :
2024-10-27 00:21:10,765 ERROR    'MyLogger' object has no attribute 'flush'
2024-10-27 01:14:17,556 INFO     >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2024-10-27 01:14:17,557 INFO     Starting up
2024-10-27 01:14:17,557 INFO     Time delay default is: 300 seconds
2024-10-27 01:14:17,557 INFO     Create Gracekiller class
2024-10-27 01:14:17,557 INFO     End Start up. Starting while loop
2024-10-27 01:14:17,557 INFO     >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2024-10-27 01:14:17,557 INFO     --------------------------------------------------------------
2024-10-27 01:14:17,989 ERROR    Traceback (most recent call last):
2024-10-27 01:14:17,989 ERROR      File "/var/www/feeder/feeder/feederTimeService.py", line 179, in <module>
2024-10-27 01:14:17,989 ERROR    output = commonTasks.update_spreadsheet()
2024-10-27 01:14:17,989 ERROR    ^
2024-10-27 01:14:17,989 ERROR    ^
2024-10-27 01:14:17,989 ERROR    ^
2024-10-27 01:14:17,989 ERROR    ^
2024-10-27 01:14:17,989 ERROR    ^
2024-10-27 01:14:17,989 ERROR    ^
2024-10-27 01:14:17,989 ERROR    ^
2024-10-27 01:14:17,990 ERROR    ^
2024-10-27 01:14:17,990 ERROR    ^
2024-10-27 01:14:17,990 ERROR    ^
2024-10-27 01:14:17,990 ERROR    ^
2024-10-27 01:14:17,990 ERROR    ^
2024-10-27 01:14:17,990 ERROR    ^
2024-10-27 01:14:17,990 ERROR    ^
2024-10-27 01:14:17,990 ERROR    ^
2024-10-27 01:14:17,990 ERROR    ^
2024-10-27 01:14:17,990 ERROR    ^
2024-10-27 01:14:17,990 ERROR    ^
2024-10-27 01:14:17,990 ERROR    ^
2024-10-27 01:14:17,990 ERROR    ^
2024-10-27 01:14:17,990 ERROR    ^
2024-10-27 01:14:17,990 ERROR    ^
2024-10-27 01:14:17,990 ERROR    ^
2024-10-27 01:14:17,990 ERROR    ^
2024-10-27 01:14:17,990 ERROR    ^
2024-10-27 01:14:17,990 ERROR    ^
2024-10-27 01:14:17,990 ERROR    ^
2024-10-27 01:14:17,990 ERROR    ^
2024-10-27 01:14:17,990 ERROR    ^
2024-10-27 01:14:17,990 ERROR    ^
2024-10-27 01:14:17,990 ERROR    ^
2024-10-27 01:14:17,990 ERROR    ^
2024-10-27 01:14:17,990 ERROR      File "/var/www/feeder/feeder/commonTasks.py", line 203, in update_spreadsheet
2024-10-27 01:14:17,990 ERROR    sheet = client.open(spreadsheetFileName).sheet1
2024-10-27 01:14:17,990 ERROR    ^
2024-10-27 01:14:17,990 ERROR    ^
2024-10-27 01:14:17,990 ERROR    ^
2024-10-27 01:14:17,991 ERROR    ^
2024-10-27 01:14:17,991 ERROR    ^
2024-10-27 01:14:17,991 ERROR    ^
2024-10-27 01:14:17,991 ERROR    ^
2024-10-27 01:14:17,991 ERROR    ^
2024-10-27 01:14:17,991 ERROR    ^
2024-10-27 01:14:17,991 ERROR    ^
2024-10-27 01:14:17,991 ERROR    ^
2024-10-27 01:14:17,991 ERROR    ^
2024-10-27 01:14:17,991 ERROR    ^
2024-10-27 01:14:17,991 ERROR    ^
2024-10-27 01:14:17,991 ERROR    ^
2024-10-27 01:14:17,991 ERROR    ^
2024-10-27 01:14:17,991 ERROR    ^
2024-10-27 01:14:17,991 ERROR    ^
2024-10-27 01:14:17,991 ERROR    ^
2024-10-27 01:14:17,991 ERROR    ^
2024-10-27 01:14:17,991 ERROR    ^
2024-10-27 01:14:17,991 ERROR    ^
2024-10-27 01:14:17,991 ERROR    ^
2024-10-27 01:14:17,991 ERROR    ^
2024-10-27 01:14:17,991 ERROR    ^
2024-10-27 01:14:17,991 ERROR    ^
2024-10-27 01:14:17,991 ERROR    ^
2024-10-27 01:14:17,991 ERROR    ^
2024-10-27 01:14:17,991 ERROR    ^
2024-10-27 01:14:17,991 ERROR    ^
2024-10-27 01:14:17,991 ERROR    ^
2024-10-27 01:14:17,991 ERROR    ^
2024-10-27 01:14:17,991 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/gspread/client.py", line 132, in open
2024-10-27 01:14:17,992 ERROR    spreadsheet_files, response = self._list_spreadsheet_files(title, folder_id)
2024-10-27 01:14:17,992 ERROR    ^
2024-10-27 01:14:17,992 ERROR    ^
2024-10-27 01:14:17,992 ERROR    ^
2024-10-27 01:14:17,992 ERROR    ^
2024-10-27 01:14:17,992 ERROR    ^
2024-10-27 01:14:17,992 ERROR    ^
2024-10-27 01:14:17,992 ERROR    ^
2024-10-27 01:14:17,992 ERROR    ^
2024-10-27 01:14:17,992 ERROR    ^
2024-10-27 01:14:17,992 ERROR    ^
2024-10-27 01:14:17,993 ERROR    ^
2024-10-27 01:14:17,993 ERROR    ^
2024-10-27 01:14:17,993 ERROR    ^
2024-10-27 01:14:17,993 ERROR    ^
2024-10-27 01:14:17,993 ERROR    ^
2024-10-27 01:14:17,993 ERROR    ^
2024-10-27 01:14:17,993 ERROR    ^
2024-10-27 01:14:17,993 ERROR    ^
2024-10-27 01:14:17,993 ERROR    ^
2024-10-27 01:14:17,993 ERROR    ^
2024-10-27 01:14:17,993 ERROR    ^
2024-10-27 01:14:17,993 ERROR    ^
2024-10-27 01:14:17,993 ERROR    ^
2024-10-27 01:14:17,993 ERROR    ^
2024-10-27 01:14:17,993 ERROR    ^
2024-10-27 01:14:17,993 ERROR    ^
2024-10-27 01:14:17,993 ERROR    ^
2024-10-27 01:14:17,993 ERROR    ^
2024-10-27 01:14:17,993 ERROR    ^
2024-10-27 01:14:17,993 ERROR    ^
2024-10-27 01:14:17,993 ERROR    ^
2024-10-27 01:14:17,993 ERROR    ^
2024-10-27 01:14:17,993 ERROR    ^
2024-10-27 01:14:17,993 ERROR    ^
2024-10-27 01:14:17,993 ERROR    ^
2024-10-27 01:14:17,993 ERROR    ^
2024-10-27 01:14:17,993 ERROR    ^
2024-10-27 01:14:17,993 ERROR    ^
2024-10-27 01:14:17,993 ERROR    ^
2024-10-27 01:14:17,993 ERROR    ^
2024-10-27 01:14:17,993 ERROR    ^
2024-10-27 01:14:17,993 ERROR    ^
2024-10-27 01:14:17,993 ERROR    ^
2024-10-27 01:14:17,993 ERROR    ^
2024-10-27 01:14:17,993 ERROR    ^
2024-10-27 01:14:17,993 ERROR    ^
2024-10-27 01:14:17,993 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/gspread/client.py", line 105, in _list_spreadsheet_files
2024-10-27 01:14:17,994 ERROR    response = self.http_client.request("get", url, params=params)
2024-10-27 01:14:17,994 ERROR    ^
2024-10-27 01:14:17,994 ERROR    ^
2024-10-27 01:14:17,994 ERROR    ^
2024-10-27 01:14:17,994 ERROR    ^
2024-10-27 01:14:17,994 ERROR    ^
2024-10-27 01:14:17,994 ERROR    ^
2024-10-27 01:14:17,994 ERROR    ^
2024-10-27 01:14:17,994 ERROR    ^
2024-10-27 01:14:17,994 ERROR    ^
2024-10-27 01:14:17,994 ERROR    ^
2024-10-27 01:14:17,994 ERROR    ^
2024-10-27 01:14:17,994 ERROR    ^
2024-10-27 01:14:17,994 ERROR    ^
2024-10-27 01:14:17,994 ERROR    ^
2024-10-27 01:14:17,994 ERROR    ^
2024-10-27 01:14:17,994 ERROR    ^
2024-10-27 01:14:17,994 ERROR    ^
2024-10-27 01:14:17,994 ERROR    ^
2024-10-27 01:14:17,994 ERROR    ^
2024-10-27 01:14:17,994 ERROR    ^
2024-10-27 01:14:17,994 ERROR    ^
2024-10-27 01:14:17,994 ERROR    ^
2024-10-27 01:14:17,994 ERROR    ^
2024-10-27 01:14:17,994 ERROR    ^
2024-10-27 01:14:17,994 ERROR    ^
2024-10-27 01:14:17,994 ERROR    ^
2024-10-27 01:14:17,994 ERROR    ^
2024-10-27 01:14:17,994 ERROR    ^
2024-10-27 01:14:17,994 ERROR    ^
2024-10-27 01:14:17,994 ERROR    ^
2024-10-27 01:14:17,994 ERROR    ^
2024-10-27 01:14:17,995 ERROR    ^
2024-10-27 01:14:17,995 ERROR    ^
2024-10-27 01:14:17,995 ERROR    ^
2024-10-27 01:14:17,995 ERROR    ^
2024-10-27 01:14:17,995 ERROR    ^
2024-10-27 01:14:17,995 ERROR    ^
2024-10-27 01:14:17,995 ERROR    ^
2024-10-27 01:14:17,995 ERROR    ^
2024-10-27 01:14:17,995 ERROR    ^
2024-10-27 01:14:17,995 ERROR    ^
2024-10-27 01:14:17,995 ERROR    ^
2024-10-27 01:14:17,995 ERROR    ^
2024-10-27 01:14:17,995 ERROR    ^
2024-10-27 01:14:17,995 ERROR    ^
2024-10-27 01:14:17,995 ERROR    ^
2024-10-27 01:14:17,995 ERROR    ^
2024-10-27 01:14:17,995 ERROR    ^
2024-10-27 01:14:17,995 ERROR    ^
2024-10-27 01:14:17,995 ERROR    ^
2024-10-27 01:14:17,995 ERROR    ^
2024-10-27 01:14:17,995 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/gspread/http_client.py", line 114, in request
2024-10-27 01:14:17,996 ERROR    response = self.session.request(
2024-10-27 01:14:17,996 ERROR    ^
2024-10-27 01:14:17,996 ERROR    ^
2024-10-27 01:14:17,997 ERROR    ^
2024-10-27 01:14:17,997 ERROR    ^
2024-10-27 01:14:17,997 ERROR    ^
2024-10-27 01:14:17,997 ERROR    ^
2024-10-27 01:14:17,997 ERROR    ^
2024-10-27 01:14:17,997 ERROR    ^
2024-10-27 01:14:17,997 ERROR    ^
2024-10-27 01:14:17,997 ERROR    ^
2024-10-27 01:14:17,997 ERROR    ^
2024-10-27 01:14:17,997 ERROR    ^
2024-10-27 01:14:17,997 ERROR    ^
2024-10-27 01:14:17,997 ERROR    ^
2024-10-27 01:14:17,997 ERROR    ^
2024-10-27 01:14:17,997 ERROR    ^
2024-10-27 01:14:17,997 ERROR    ^
2024-10-27 01:14:17,997 ERROR    ^
2024-10-27 01:14:17,997 ERROR    ^
2024-10-27 01:14:17,997 ERROR    ^
2024-10-27 01:14:17,997 ERROR    ^
2024-10-27 01:14:17,997 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/google/auth/transport/requests.py", line 534, in request
2024-10-27 01:14:17,999 ERROR    self.credentials.before_request(auth_request, method, url, request_headers)
2024-10-27 01:14:17,999 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/google/auth/credentials.py", line 228, in before_request
2024-10-27 01:14:18,001 ERROR    self._blocking_refresh(request)
2024-10-27 01:14:18,001 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/google/auth/credentials.py", line 191, in _blocking_refresh
2024-10-27 01:14:18,001 ERROR    self.refresh(request)
2024-10-27 01:14:18,001 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/google/oauth2/service_account.py", line 446, in refresh
2024-10-27 01:14:18,003 ERROR    access_token, expiry, _ = _client.jwt_grant(
2024-10-27 01:14:18,003 ERROR    ^
2024-10-27 01:14:18,003 ERROR    ^
2024-10-27 01:14:18,003 ERROR    ^
2024-10-27 01:14:18,003 ERROR    ^
2024-10-27 01:14:18,004 ERROR    ^
2024-10-27 01:14:18,004 ERROR    ^
2024-10-27 01:14:18,004 ERROR    ^
2024-10-27 01:14:18,004 ERROR    ^
2024-10-27 01:14:18,004 ERROR    ^
2024-10-27 01:14:18,004 ERROR    ^
2024-10-27 01:14:18,004 ERROR    ^
2024-10-27 01:14:18,004 ERROR    ^
2024-10-27 01:14:18,004 ERROR    ^
2024-10-27 01:14:18,004 ERROR    ^
2024-10-27 01:14:18,004 ERROR    ^
2024-10-27 01:14:18,004 ERROR    ^
2024-10-27 01:14:18,004 ERROR    ^
2024-10-27 01:14:18,004 ERROR    ^
2024-10-27 01:14:18,004 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/google/oauth2/_client.py", line 298, in jwt_grant
2024-10-27 01:14:18,005 ERROR    response_data = _token_endpoint_request(
2024-10-27 01:14:18,005 ERROR    ^
2024-10-27 01:14:18,005 ERROR    ^
2024-10-27 01:14:18,005 ERROR    ^
2024-10-27 01:14:18,005 ERROR    ^
2024-10-27 01:14:18,005 ERROR    ^
2024-10-27 01:14:18,005 ERROR    ^
2024-10-27 01:14:18,005 ERROR    ^
2024-10-27 01:14:18,005 ERROR    ^
2024-10-27 01:14:18,005 ERROR    ^
2024-10-27 01:14:18,005 ERROR    ^
2024-10-27 01:14:18,005 ERROR    ^
2024-10-27 01:14:18,005 ERROR    ^
2024-10-27 01:14:18,006 ERROR    ^
2024-10-27 01:14:18,006 ERROR    ^
2024-10-27 01:14:18,006 ERROR    ^
2024-10-27 01:14:18,006 ERROR    ^
2024-10-27 01:14:18,006 ERROR    ^
2024-10-27 01:14:18,006 ERROR    ^
2024-10-27 01:14:18,006 ERROR    ^
2024-10-27 01:14:18,006 ERROR    ^
2024-10-27 01:14:18,006 ERROR    ^
2024-10-27 01:14:18,006 ERROR    ^
2024-10-27 01:14:18,006 ERROR    ^
2024-10-27 01:14:18,006 ERROR    ^
2024-10-27 01:14:18,006 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/google/oauth2/_client.py", line 269, in _token_endpoint_request
2024-10-27 01:14:18,006 ERROR    _handle_error_response(response_data, retryable_error)
2024-10-27 01:14:18,006 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/google/oauth2/_client.py", line 68, in _handle_error_response
2024-10-27 01:14:18,006 ERROR    raise exceptions.RefreshError(
2024-10-27 01:14:18,006 ERROR    google.auth.exceptions
2024-10-27 01:14:18,006 ERROR    .
2024-10-27 01:14:18,006 ERROR    RefreshError
2024-10-27 01:14:18,006 ERROR    :
2024-10-27 01:14:18,006 ERROR    ('invalid_grant: Invalid JWT Signature.', {'error': 'invalid_grant', 'error_description': 'Invalid JWT Signature.'})
2024-10-27 01:14:18,007 ERROR    Exception ignored in:
2024-10-27 01:14:18,007 ERROR    <__main__.MyLogger object at 0xffff94452ae0>
2024-10-27 01:14:18,007 ERROR    AttributeError
2024-10-27 01:14:18,007 ERROR    :
2024-10-27 01:14:18,007 ERROR    'MyLogger' object has no attribute 'flush'
2024-10-27 01:14:18,007 ERROR    Exception ignored in sys.unraisablehook
2024-10-27 01:14:18,007 ERROR    :
2024-10-27 01:14:18,007 ERROR    <built-in function unraisablehook>
2024-10-27 01:14:18,007 ERROR    AttributeError
2024-10-27 01:14:18,007 ERROR    :
2024-10-27 01:14:18,007 ERROR    'MyLogger' object has no attribute 'flush'
2024-10-27 01:22:07,344 INFO     >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2024-10-27 01:22:07,346 INFO     Starting up
2024-10-27 01:22:07,346 INFO     Time delay default is: 300 seconds
2024-10-27 01:22:07,346 INFO     Create Gracekiller class
2024-10-27 01:22:07,346 INFO     End Start up. Starting while loop
2024-10-27 01:22:07,346 INFO     >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2024-10-27 01:22:07,346 INFO     --------------------------------------------------------------
2024-10-27 01:22:30,546 ERROR    Traceback (most recent call last):
2024-10-27 01:22:30,546 ERROR      File "/var/www/feeder/feeder/feederTimeService.py", line 179, in <module>
2024-10-27 01:22:30,546 ERROR    output = commonTasks.update_spreadsheet()
2024-10-27 01:22:30,546 ERROR    ^
2024-10-27 01:22:30,546 ERROR    ^
2024-10-27 01:22:30,546 ERROR    ^
2024-10-27 01:22:30,546 ERROR    ^
2024-10-27 01:22:30,546 ERROR    ^
2024-10-27 01:22:30,546 ERROR    ^
2024-10-27 01:22:30,546 ERROR    ^
2024-10-27 01:22:30,547 ERROR    ^
2024-10-27 01:22:30,547 ERROR    ^
2024-10-27 01:22:30,547 ERROR    ^
2024-10-27 01:22:30,547 ERROR    ^
2024-10-27 01:22:30,547 ERROR    ^
2024-10-27 01:22:30,547 ERROR    ^
2024-10-27 01:22:30,547 ERROR    ^
2024-10-27 01:22:30,547 ERROR    ^
2024-10-27 01:22:30,547 ERROR    ^
2024-10-27 01:22:30,547 ERROR    ^
2024-10-27 01:22:30,547 ERROR    ^
2024-10-27 01:22:30,547 ERROR    ^
2024-10-27 01:22:30,547 ERROR    ^
2024-10-27 01:22:30,547 ERROR    ^
2024-10-27 01:22:30,547 ERROR    ^
2024-10-27 01:22:30,547 ERROR    ^
2024-10-27 01:22:30,547 ERROR    ^
2024-10-27 01:22:30,547 ERROR    ^
2024-10-27 01:22:30,547 ERROR    ^
2024-10-27 01:22:30,547 ERROR    ^
2024-10-27 01:22:30,547 ERROR    ^
2024-10-27 01:22:30,547 ERROR    ^
2024-10-27 01:22:30,547 ERROR    ^
2024-10-27 01:22:30,547 ERROR    ^
2024-10-27 01:22:30,547 ERROR    ^
2024-10-27 01:22:30,547 ERROR      File "/var/www/feeder/feeder/commonTasks.py", line 203, in update_spreadsheet
2024-10-27 01:22:30,550 ERROR    sheet = client.open(spreadsheetFileName).sheet1
2024-10-27 01:22:30,550 ERROR    ^
2024-10-27 01:22:30,550 ERROR    ^
2024-10-27 01:22:30,550 ERROR    ^
2024-10-27 01:22:30,550 ERROR    ^
2024-10-27 01:22:30,550 ERROR    ^
2024-10-27 01:22:30,551 ERROR    ^
2024-10-27 01:22:30,551 ERROR    ^
2024-10-27 01:22:30,551 ERROR    ^
2024-10-27 01:22:30,551 ERROR    ^
2024-10-27 01:22:30,551 ERROR    ^
2024-10-27 01:22:30,551 ERROR    ^
2024-10-27 01:22:30,551 ERROR    ^
2024-10-27 01:22:30,551 ERROR    ^
2024-10-27 01:22:30,551 ERROR    ^
2024-10-27 01:22:30,551 ERROR    ^
2024-10-27 01:22:30,551 ERROR    ^
2024-10-27 01:22:30,551 ERROR    ^
2024-10-27 01:22:30,551 ERROR    ^
2024-10-27 01:22:30,551 ERROR    ^
2024-10-27 01:22:30,551 ERROR    ^
2024-10-27 01:22:30,551 ERROR    ^
2024-10-27 01:22:30,551 ERROR    ^
2024-10-27 01:22:30,551 ERROR    ^
2024-10-27 01:22:30,551 ERROR    ^
2024-10-27 01:22:30,551 ERROR    ^
2024-10-27 01:22:30,551 ERROR    ^
2024-10-27 01:22:30,551 ERROR    ^
2024-10-27 01:22:30,551 ERROR    ^
2024-10-27 01:22:30,551 ERROR    ^
2024-10-27 01:22:30,551 ERROR    ^
2024-10-27 01:22:30,551 ERROR    ^
2024-10-27 01:22:30,551 ERROR    ^
2024-10-27 01:22:30,551 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/gspread/client.py", line 132, in open
2024-10-27 01:22:30,552 ERROR    spreadsheet_files, response = self._list_spreadsheet_files(title, folder_id)
2024-10-27 01:22:30,552 ERROR    ^
2024-10-27 01:22:30,552 ERROR    ^
2024-10-27 01:22:30,552 ERROR    ^
2024-10-27 01:22:30,552 ERROR    ^
2024-10-27 01:22:30,552 ERROR    ^
2024-10-27 01:22:30,553 ERROR    ^
2024-10-27 01:22:30,553 ERROR    ^
2024-10-27 01:22:30,553 ERROR    ^
2024-10-27 01:22:30,553 ERROR    ^
2024-10-27 01:22:30,553 ERROR    ^
2024-10-27 01:22:30,553 ERROR    ^
2024-10-27 01:22:30,553 ERROR    ^
2024-10-27 01:22:30,553 ERROR    ^
2024-10-27 01:22:30,553 ERROR    ^
2024-10-27 01:22:30,553 ERROR    ^
2024-10-27 01:22:30,553 ERROR    ^
2024-10-27 01:22:30,553 ERROR    ^
2024-10-27 01:22:30,553 ERROR    ^
2024-10-27 01:22:30,553 ERROR    ^
2024-10-27 01:22:30,553 ERROR    ^
2024-10-27 01:22:30,553 ERROR    ^
2024-10-27 01:22:30,553 ERROR    ^
2024-10-27 01:22:30,553 ERROR    ^
2024-10-27 01:22:30,553 ERROR    ^
2024-10-27 01:22:30,553 ERROR    ^
2024-10-27 01:22:30,553 ERROR    ^
2024-10-27 01:22:30,553 ERROR    ^
2024-10-27 01:22:30,553 ERROR    ^
2024-10-27 01:22:30,553 ERROR    ^
2024-10-27 01:22:30,553 ERROR    ^
2024-10-27 01:22:30,553 ERROR    ^
2024-10-27 01:22:30,553 ERROR    ^
2024-10-27 01:22:30,553 ERROR    ^
2024-10-27 01:22:30,553 ERROR    ^
2024-10-27 01:22:30,553 ERROR    ^
2024-10-27 01:22:30,553 ERROR    ^
2024-10-27 01:22:30,553 ERROR    ^
2024-10-27 01:22:30,553 ERROR    ^
2024-10-27 01:22:30,553 ERROR    ^
2024-10-27 01:22:30,554 ERROR    ^
2024-10-27 01:22:30,554 ERROR    ^
2024-10-27 01:22:30,554 ERROR    ^
2024-10-27 01:22:30,554 ERROR    ^
2024-10-27 01:22:30,554 ERROR    ^
2024-10-27 01:22:30,554 ERROR    ^
2024-10-27 01:22:30,554 ERROR    ^
2024-10-27 01:22:30,554 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/gspread/client.py", line 105, in _list_spreadsheet_files
2024-10-27 01:22:30,554 ERROR    response = self.http_client.request("get", url, params=params)
2024-10-27 01:22:30,554 ERROR    ^
2024-10-27 01:22:30,554 ERROR    ^
2024-10-27 01:22:30,554 ERROR    ^
2024-10-27 01:22:30,554 ERROR    ^
2024-10-27 01:22:30,554 ERROR    ^
2024-10-27 01:22:30,554 ERROR    ^
2024-10-27 01:22:30,554 ERROR    ^
2024-10-27 01:22:30,554 ERROR    ^
2024-10-27 01:22:30,554 ERROR    ^
2024-10-27 01:22:30,554 ERROR    ^
2024-10-27 01:22:30,554 ERROR    ^
2024-10-27 01:22:30,554 ERROR    ^
2024-10-27 01:22:30,554 ERROR    ^
2024-10-27 01:22:30,554 ERROR    ^
2024-10-27 01:22:30,554 ERROR    ^
2024-10-27 01:22:30,554 ERROR    ^
2024-10-27 01:22:30,554 ERROR    ^
2024-10-27 01:22:30,555 ERROR    ^
2024-10-27 01:22:30,555 ERROR    ^
2024-10-27 01:22:30,555 ERROR    ^
2024-10-27 01:22:30,555 ERROR    ^
2024-10-27 01:22:30,555 ERROR    ^
2024-10-27 01:22:30,555 ERROR    ^
2024-10-27 01:22:30,555 ERROR    ^
2024-10-27 01:22:30,555 ERROR    ^
2024-10-27 01:22:30,555 ERROR    ^
2024-10-27 01:22:30,555 ERROR    ^
2024-10-27 01:22:30,555 ERROR    ^
2024-10-27 01:22:30,555 ERROR    ^
2024-10-27 01:22:30,555 ERROR    ^
2024-10-27 01:22:30,555 ERROR    ^
2024-10-27 01:22:30,555 ERROR    ^
2024-10-27 01:22:30,555 ERROR    ^
2024-10-27 01:22:30,555 ERROR    ^
2024-10-27 01:22:30,555 ERROR    ^
2024-10-27 01:22:30,555 ERROR    ^
2024-10-27 01:22:30,555 ERROR    ^
2024-10-27 01:22:30,555 ERROR    ^
2024-10-27 01:22:30,555 ERROR    ^
2024-10-27 01:22:30,555 ERROR    ^
2024-10-27 01:22:30,555 ERROR    ^
2024-10-27 01:22:30,555 ERROR    ^
2024-10-27 01:22:30,555 ERROR    ^
2024-10-27 01:22:30,555 ERROR    ^
2024-10-27 01:22:30,555 ERROR    ^
2024-10-27 01:22:30,555 ERROR    ^
2024-10-27 01:22:30,555 ERROR    ^
2024-10-27 01:22:30,555 ERROR    ^
2024-10-27 01:22:30,555 ERROR    ^
2024-10-27 01:22:30,556 ERROR    ^
2024-10-27 01:22:30,556 ERROR    ^
2024-10-27 01:22:30,556 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/gspread/http_client.py", line 114, in request
2024-10-27 01:22:30,556 ERROR    response = self.session.request(
2024-10-27 01:22:30,556 ERROR    ^
2024-10-27 01:22:30,556 ERROR    ^
2024-10-27 01:22:30,556 ERROR    ^
2024-10-27 01:22:30,556 ERROR    ^
2024-10-27 01:22:30,556 ERROR    ^
2024-10-27 01:22:30,556 ERROR    ^
2024-10-27 01:22:30,556 ERROR    ^
2024-10-27 01:22:30,556 ERROR    ^
2024-10-27 01:22:30,556 ERROR    ^
2024-10-27 01:22:30,557 ERROR    ^
2024-10-27 01:22:30,557 ERROR    ^
2024-10-27 01:22:30,557 ERROR    ^
2024-10-27 01:22:30,557 ERROR    ^
2024-10-27 01:22:30,557 ERROR    ^
2024-10-27 01:22:30,557 ERROR    ^
2024-10-27 01:22:30,557 ERROR    ^
2024-10-27 01:22:30,557 ERROR    ^
2024-10-27 01:22:30,557 ERROR    ^
2024-10-27 01:22:30,557 ERROR    ^
2024-10-27 01:22:30,557 ERROR    ^
2024-10-27 01:22:30,557 ERROR    ^
2024-10-27 01:22:30,557 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/google/auth/transport/requests.py", line 534, in request
2024-10-27 01:22:30,558 ERROR    self.credentials.before_request(auth_request, method, url, request_headers)
2024-10-27 01:22:30,558 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/google/auth/credentials.py", line 228, in before_request
2024-10-27 01:22:30,558 ERROR    self._blocking_refresh(request)
2024-10-27 01:22:30,558 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/google/auth/credentials.py", line 191, in _blocking_refresh
2024-10-27 01:22:30,558 ERROR    self.refresh(request)
2024-10-27 01:22:30,559 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/google/oauth2/service_account.py", line 446, in refresh
2024-10-27 01:22:30,559 ERROR    access_token, expiry, _ = _client.jwt_grant(
2024-10-27 01:22:30,559 ERROR    ^
2024-10-27 01:22:30,560 ERROR    ^
2024-10-27 01:22:30,560 ERROR    ^
2024-10-27 01:22:30,560 ERROR    ^
2024-10-27 01:22:30,560 ERROR    ^
2024-10-27 01:22:30,560 ERROR    ^
2024-10-27 01:22:30,560 ERROR    ^
2024-10-27 01:22:30,560 ERROR    ^
2024-10-27 01:22:30,560 ERROR    ^
2024-10-27 01:22:30,560 ERROR    ^
2024-10-27 01:22:30,560 ERROR    ^
2024-10-27 01:22:30,560 ERROR    ^
2024-10-27 01:22:30,560 ERROR    ^
2024-10-27 01:22:30,560 ERROR    ^
2024-10-27 01:22:30,560 ERROR    ^
2024-10-27 01:22:30,560 ERROR    ^
2024-10-27 01:22:30,560 ERROR    ^
2024-10-27 01:22:30,560 ERROR    ^
2024-10-27 01:22:30,560 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/google/oauth2/_client.py", line 298, in jwt_grant
2024-10-27 01:22:30,560 ERROR    response_data = _token_endpoint_request(
2024-10-27 01:22:30,560 ERROR    ^
2024-10-27 01:22:30,560 ERROR    ^
2024-10-27 01:22:30,561 ERROR    ^
2024-10-27 01:22:30,561 ERROR    ^
2024-10-27 01:22:30,561 ERROR    ^
2024-10-27 01:22:30,561 ERROR    ^
2024-10-27 01:22:30,561 ERROR    ^
2024-10-27 01:22:30,561 ERROR    ^
2024-10-27 01:22:30,561 ERROR    ^
2024-10-27 01:22:30,561 ERROR    ^
2024-10-27 01:22:30,561 ERROR    ^
2024-10-27 01:22:30,561 ERROR    ^
2024-10-27 01:22:30,561 ERROR    ^
2024-10-27 01:22:30,561 ERROR    ^
2024-10-27 01:22:30,561 ERROR    ^
2024-10-27 01:22:30,561 ERROR    ^
2024-10-27 01:22:30,561 ERROR    ^
2024-10-27 01:22:30,561 ERROR    ^
2024-10-27 01:22:30,561 ERROR    ^
2024-10-27 01:22:30,561 ERROR    ^
2024-10-27 01:22:30,561 ERROR    ^
2024-10-27 01:22:30,561 ERROR    ^
2024-10-27 01:22:30,561 ERROR    ^
2024-10-27 01:22:30,561 ERROR    ^
2024-10-27 01:22:30,561 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/google/oauth2/_client.py", line 269, in _token_endpoint_request
2024-10-27 01:22:30,561 ERROR    _handle_error_response(response_data, retryable_error)
2024-10-27 01:22:30,561 ERROR      File "/var/www/feeder/lib/python3.12/site-packages/google/oauth2/_client.py", line 68, in _handle_error_response
2024-10-27 01:22:30,561 ERROR    raise exceptions.RefreshError(
2024-10-27 01:22:30,561 ERROR    google.auth.exceptions
2024-10-27 01:22:30,561 ERROR    .
2024-10-27 01:22:30,561 ERROR    RefreshError
2024-10-27 01:22:30,561 ERROR    :
2024-10-27 01:22:30,561 ERROR    ('invalid_grant: Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values in the JWT claim.', {'error': 'invalid_grant', 'error_description': 'Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values in the JWT claim.'})
2024-10-27 01:22:30,562 ERROR    Exception ignored in:
2024-10-27 01:22:30,562 ERROR    <__main__.MyLogger object at 0xffff98822e10>
2024-10-27 01:22:30,562 ERROR    AttributeError
2024-10-27 01:22:30,562 ERROR    :
2024-10-27 01:22:30,562 ERROR    'MyLogger' object has no attribute 'flush'
2024-10-27 01:22:30,562 ERROR    Exception ignored in sys.unraisablehook
2024-10-27 01:22:30,562 ERROR    :
2024-10-27 01:22:30,562 ERROR    <built-in function unraisablehook>
2024-10-27 01:22:30,562 ERROR    AttributeError
2024-10-27 01:22:30,562 ERROR    :
2024-10-27 01:22:30,562 ERROR    'MyLogger' object has no attribute 'flush'
